#################################################################
#                                                               #
#                      Packages/Good Night                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:


#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:

#################################################################
#                                                               #
#                           Switches                            #
#                                                               #
#################################################################

switch:
  - platform: command_line
    switches:
      goodnight:
        friendly_name: "Goodnight"
        command_on: python3 /config/python_scripts/goodnight.py

#################################################################
#                                                               #
#                        Input Boolean                          #
#                                                               #
#################################################################

input_boolean:
  morning_script_run:
    name: Morning Script Run
    initial: off
    icon: mdi:delete-variant

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:
## Runs a script to turn everything off when I head upstairs to bed
  - alias: 'Goodnight'
    trigger:
    - platform: state
      entity_id: switch.goodnight
      to: 'on'
    # condition:
    # - condition: numeric_state
    #   entity_id: sensor.door_count
    #   below: '1'
    # - condition: numeric_state
    #   entity_id: sensor.window_count
    #   below: '1'
    action:
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.kodi
        message: >
          <speak>
            Goodnight, sweet dreams, I'll take it from here
          </speak>
        cache: true
    - service: script.1527969569077

## Notify if there are any open doors before setting the alarm from good night script
  - alias: 'Open Doors Notification on Goodnight'
    trigger:
    - platform: state
      entity_id: switch.goodnight
      to: 'on'
    condition:
    - condition: numeric_state
      entity_id: sensor.door_count
      above: '0'
    action:
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.kodi
        message: >
          <speak>
            There are still doors open maybe you should close them first.
          </speak>
        cache: true

## Notify if there are any open windows before setting the alarm from good night script
  - alias: 'Open Doors Notification on Goodnight'
    trigger:
    - platform: state
      entity_id: switch.goodnight
      to: 'on'
    condition:
    - condition: numeric_state
      entity_id: sensor.window_count
      above: '0'
    action:
    - delay: '00:00:20'
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.kodi
        message: >
          <speak>
            There are still windows open maybe you should close them first.
          </speak>
        cache: true
