####################################################
#                                                  #
#                      Kodi                        #
#                                                  #
####################################################

- platform: kodi
  host: 192.168.1.61
  name: Kodi

####################################################
#                                                  #
#                      iTunes                      #
#                                                  #
####################################################

- platform: itunes
  host: 192.168.1.13
  password: kodi
  name: Computer
